{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stacklens-platform.fullname" . }}
  labels:
    {{- include "stacklens-platform.labels" . | nindent 4 }}
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "stacklens-platform.gateway.name" . }}
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "stacklens-platform.ui.name" . }}
                port:
                  number: 80
{{- end }}
