{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stacklens-platform.gateway.name" . }}
  labels:
    {{- include "stacklens-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
  {{- end }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  selector:
    matchLabels:
      {{- include "stacklens-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "stacklens-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gateway
          image: {{ printf "%s/stacklens-gateway:%s" .Values.images.registry .Values.images.tag | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "stacklens-platform.fullname" . }}-gateway-env
          env:
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: {{ include "stacklens-platform.secretName" . }}
                  key: Jwt__Secret
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
{{- end }}
